### ISSUE TITLE
Registration turned off, but is still possible with wpcm_submit_car_form shortcode

### ISSUE THREAD

**Issue by ehrig** [barrykooij/wp-car-manager#116]
When "Anyone can register“ option is disabled in WordPress adminarea, visitors can still register and submit cars using the wpcm_submit_car_form shortcode.

**Comment by barrykooij** [comment]
You're talking about the WP native "Anyone can register" option? Because WPCM comes with its own setting for this:

![image](https://cloud.githubusercontent.com/assets/2846594/15500642/e8748d26-21a9-11e6-83f7-55697b571664.png)

When that is not checked, visitors can't create an account.
