### ISSUE TITLE
Somehow featured image doesn't seem to work!?

### ISSUE THREAD

**Issue by pgroot91** [barrykooij/wp-car-manager#136]
Somehow featured image doesn't seem to work!? Just showing the placeholder in frontend and backend.

**Comment by barrykooij** [comment]
What version are you running? Does the problem still exists with latest master? We're about to release 1.3.0 (current master).

**Comment by Zaanmedia** [comment]
Yes current master 1.3.0 and latest wp 4.5.3. I tried to disable all plugins and go back to a standerd wp theme but that was not the problem. the gallery was still not updating/changing the featured placeholder.

**Comment by Zaanmedia** [comment]
Somehow it's working now in all themes included custom ones... added this to the custom template add_theme_support( 'post-thumbnails' ); and now its working in the twenty fifteen also strange why id didn't work the first time i switched the theme... anyhow it works now! Is it not possible to include the add theme support somehow in the plugin itself for featured image? Thanks

**Comment by barrykooij** [comment]
That's very odd! `add_theme_support();` is something themes should declare. I'll look into this for the next release to see if we can add this our self but I remember from another one of my plugins that this might cause some issues with other themes (if it's already declared).

**Comment by Zaanmedia** [comment]
Maybe this source can be usefull...

https://pippinsplugins.com/check-if-theme-supports-post-thumbnails/

**Comment by barrykooij** [comment]
Fixed at 79568b41d8301d5ec5f4c1958372cc5ec05ad208
