### ISSUE TITLE
Link structure does it make any sence? Don't know...

### ISSUE THREAD

**Issue by Zaanmedia** [barrykooij/wp-car-manager#137]
Ik hou het voor het gemak maar even bij gewoon Nederlands. 

Je aanbod plaats je bijv. op de pagina occasions.

www.domein.nl/occasions/

Klikt vervolgens op een voertuig/auto. En vervolgens word de link.

www.domein.nl/voertuig/auto-titel

Is het niet mogelijk of beter voor de structuur als /voertuig aangepast veranderd word in de parent pagina waar de voertuigen zich bevinden. Ik vraag me af of dit invloed heeft op bijv. zoekmachines. 

www.domein.nl/occasions/auto-titel

Misschien is dit allemaal wat vergezocht maar ben benieuwd wat jou visie hier op is.

**Comment by barrykooij** [comment]
Dit is op dit moment wel mogelijk maar doen wij niet standaard. WordPress bouwt de permalinks (dus URL structuur) op vanuit het post type. De pagina waar je de listing overview op plaats heeft (voor WordPress) niks te maken met de single URL (detail pagina) van het voertuig. 

Ik begrijp dat je dit wilt voor je eigen website, en dit kan dus via een filter in de post type registratie. Maar dit default doen is niet volgens WP standaarden.
