### ISSUE TITLE
Display cars on dashboard for super admins, in WordPress MU environment.

### ISSUE THREAD

**Issue by mukundthanki** [barrykooij/wp-car-manager#147]
Hello,
First, thanks for great plugin. its very nicely written.
I am using plugin on WordPress MU Environment, In which I need to display cars for super admins on dashboard( "My cars" ), but as I dig into code I found below snippet, where we display cars by authors.

```
$vehicles        = $vehicle_manager->get_vehicles( array(), $sort, - 1, array(
            'author'      => get_current_user_id(),
            'post_status' => apply_filters( 'wpcm_dashboard_post_status', array( 'publish', 'expired', 'pending' ) )
        ) );
```

Here, is there any way I can override `'author'      => get_current_user_id(),` 

Can you please introduce filter for `$extra_args` so we can manipulate|add|update data on the fly ?

Can you please provide some developer documentation like how to extend your classes in custom plugins, or extending plugin by registering new vehicle types.

Thanks

**Comment by barrykooij** [comment]
This can be filtered via the `wpcm_dashboard_get_vehicles_extra_args` filter in version 1.4 and higher.
