### ISSUE TITLE
Request to move fields rendering and container form html data to template.

### ISSUE THREAD

**Issue by mukundthanki** [barrykooij/wp-car-manager#148]
Hi,

I see `wpcm_template_submit_car_form_fields_car_data` function called using hook from `submit-car-form.php` which is container template of submit form. But above function contains html code and form data rendering.

I suggest|request to move that html code to `submit-car-form.php` so we can manipulate and extend easily.

Also I have managed to extend `get_fields` method but I could not use my method as original method called statically in above function.

Can you please provide filter or some workaround so we can add|edit built-in fields ?

Thanks

**Comment by barrykooij** [comment]
Sorry for my delayed reply. Could you please re-open this issue if it's still relevant to you?
