### ISSUE TITLE
Backend setting for listing order

### ISSUE THREAD

**Issue by pgroot91** [barrykooij/wp-car-manager#156]
See thread: https://wordpress.org/support/topic/list-the-cars-after-publication-date/

It would be nice if there is a setting in the backend for the frontend listings order. So people can choose how to display the listings order by default.

**Comment by barrykooij** [comment]
Sorry for the very late reply but like the w.org thread says, this can be done via shortcode attribute like this:
`[wpcm_cars sort='date-desc']`.

I'll make sure the documentation is up to date.
