### ISSUE TITLE
Wrong filter name on sort.php

### ISSUE THREAD

**Issue by Adhik** [barrykooij/wp-car-manager#158]
I think a wrong filter name: "wpcm_filter_mileage" is used on 
wp-car-manager/templates/listings/sort.php (line 7):

`apply_filters('wpcm_filter_mileage', array( ....`

**Comment by calvincanas** [comment]
Yes, plus it is already use in _wp-car-manager-master/templates/listings/filters/mileage.php_

**Comment by barrykooij** [comment]
Fixed at 503f25f268800321d70ea808a20569a4199f3535
