### ISSUE TITLE
Images loads very slow

### ISSUE THREAD

**Issue by dukocuk** [barrykooij/wp-car-manager#161]
When having like a couple of images 3-5 and you want to see the pictures of the car, it takes quite some time to load and show the pictures if you click on them. Sometimes nothing even happens.

**Comment by barrykooij** [comment]
Hey,

This is very odd and sounds like a server issue. We use a lightweight JavaScript library to serve the images in a popup but your server still needs to serve the files to the browser. Please check with your host to see if there's an issue on the server you're using.

Kind Regards,

Barry Kooij
