### ISSUE TITLE
Different types of cars

### ISSUE THREAD

**Issue by dukocuk** [barrykooij/wp-car-manager#162]
Would be nice to choose between different types of cars like small/big types.
It will then be easier to place a shortcode on pages so we only see certain types of cars on certain pages.

**Comment by barrykooij** [comment]
I agree. We're working on a solution that will allow users to add/modify/delete car data. This will also make it possible for you to add a data field like "Car type". Please subscribe to our newsletter to be notified when we release this extension: https://www.wpcarmanager.com/subscribe-to-our-newsletter/

**Comment by verocom** [comment]
Did you came up with a solution so far ?! I need this in my project right since my client want to sell Cars & Tractors. Thanks ! :)
