### ISSUE TITLE
Can't edit make

### ISSUE THREAD

**Issue by willrbc** [barrykooij/wp-car-manager#166]
I've just installed the plugin and have created 2 makes.  Volvo and VW,

When I click to edit the make my local wordpress environment it never loads. The screen is black and the loading indicator just spins.

In the console I get:

````
GET http://localhost:8888/wp-admin/edit.php?post_type=wpcm_vehicle&page=wpcm-makes&edit=4 net::ERR_INCOMPLETE_CHUNKED_ENCODING

**Comment by barrykooij** [comment]
Hey,

I suspect that there is a plugin or theme conflict on your website. Could you please try if the error still occurs with only this plugin activated with a default WordPress theme (e.g. twentyfifteen). I understand this can be a bit of a hassle but it's the only way we can be sure it's a bug in this plugin.

Kind Regards,

Barry Kooij

**Comment by barrykooij** [comment]
No reply since 2017. Please feel free to re-open if this issue still exists.
