### ISSUE TITLE
Adding Structural Hooks

### ISSUE THREAD

**Issue by defries** [barrykooij/wp-car-manager#167]
I love that you can overwrite certain views by overriding a template file, but I'm missing the ability to easily add content block between the different views. 

For example, if I wanted to add a CTA section between the `wpcm-vehicle-head` and `wpcm-vehicle-content` section on the single view, I would have to overwrite one or two views. Ideally, both those files have a hook in place which allows me to programattically add content between views.

For most views both a `wpcm-before-*` and `wpcm-after-*` hooks would be great. Where `*` stands for either price, image or any of the other single view template parts.

Happy to provide a pull request, but I'd need pointers on how you'd like them added.

**Comment by barrykooij** [comment]
Talked this over with @defries and this can be fixed with the existing `wpcm_before_template_part` and ` wpcm_after_template_part` actions.
