### ISSUE TITLE
Make Filter auto opens 'listing your vehicles' web page

### ISSUE THREAD

**Issue by franrb3** [barrykooij/wp-car-manager#169]
Hello. On the car listings page, when you click on the 'Make' drop down arrow, for some reason it automatically opens (https://www.wpcarmanager.com/kb/listings-page/) in a new window. This isn't something that visitors to the site would want to see when they click the arrow. 

This is my car sales page. http://www.supercarsourcing.com/sales/

How can I remove this issue please?

**Comment by cun** [comment]
@franrb3 how did you fix this?

**Comment by franrb3** [comment]
We had to get into the html code and manually take the link out. Couldn’t find any way to do it in the wordpress settings / theme options.




On 13 Nov 2017, at 22:55, Dan Cunningham <notifications@github.com<mailto:notifications@github.com>> wrote:


@franrb3<https://github.com/franrb3> how did you fix this?

**Comment by cun** [comment]
@franrb3  can you remember where said code is (which file) i've looked for it, even searched for it... I can't find it!

**Comment by barrykooij** [comment]
This is definitely not something we're doing. I suspect your theme to do this. Please contact your theme author.

**Comment by cun** [comment]
@barrykooij It's a standard install...
