### ISSUE TITLE
Frontend submission, doors are set 0 when left empty

### ISSUE THREAD

**Issue by barrykooij** [barrykooij/wp-car-manager#175]
Report:

> When adding a new car from the wordpress admin area, everything works fine. However, when we go to the front-end dashboard and add a vehicle from there, - if we leave the doors as blank - don't want them displayed - it still shows up with: Doors 0.

Probably related to data verification. Also check other integer values.

**Comment by neural-oD** [comment]
Is there a work-around to do this, so it will work with the current system, before this ticket is dealt with?
