### ISSUE TITLE
Makes and Models extension not showing in wordpress tools/import.

### ISSUE THREAD

**Issue by turkenr** [barrykooij/wp-car-manager#194]
Makes and Models extension not showing in wordpress tools/import.
Put the man folder folder in the zip into the correct wordpress folders but nothing is showing in the import section.

**Comment by pgroot91** [comment]
@turkenr not sure what you mean? Did you purchased the extension for importing or exporting? or did you purchased the make and modal syc extension?

**Comment by turkenr** [comment]
(I also wrote to the support mail). 
But to your question:
I bought the makes and models sync extension and the guide on the wp car site said that in order to install the extension i hade to:
1. Place the makes and models folder in wp-content/plugins
2. Go to Dashboard -> tools -> import and use the wp car import thats supposed to show in the import list.
But nothing comes up in the 'Dashboard -> tools -> import' list.

**Comment by pgroot91** [comment]
@turkenr unfortunately i don't have any active licenses anymore from wp-car-manager so i'm unable to confirm its broken and im unable to find local copies of it. So best thing is to wait for support. Shame that there is no way to re-download the plugins even if that include older release versions of the subscription at that time.

**Comment by turkenr** [comment]
Kk thanks, got a reply from the support that they were going to check it out.
