### ISSUE TITLE
Looks really bad when you "forget" to add images

### ISSUE THREAD

**Issue by claudiosmweb** [barrykooij/wp-car-manager#26]
![screenshot from 2015-08-11 20 50 47](https://cloud.githubusercontent.com/assets/1264099/9213624/f04efac0-406a-11e5-87bb-58e2af946615.png)

**Comment by barrykooij** [comment]
Yeah, we a placeholder image.

**Comment by barrykooij** [comment]
Closed in favor of https://github.com/barrykooij/wp-car-manager/issues/30
