### ISSUE TITLE
Link to detailed information results in Error page

### ISSUE THREAD

**Issue by Dictaat** [barrykooij/wp-car-manager#53]
I really liked the last update since now I can have the language of my website's country. However, after updating the last bug there appeared new problems. Whenever I go to the general overview and click on a link to see detailed information about a car it resulted in the Error page. Oops! That page can’t be found.

**Comment by barrykooij** [comment]
Hey Dictaat,

Sorry for missing this issue but this can be easily fixed by resaving your permalinks.

Kind Regards,

Barry Kooij

Duplicate of #46

**Comment by Dictaat** [comment]
Thnks, I like your widget.
Op 5 dec. 2015 11:33 schreef "Barry Kooij" <notifications@github.com>:
