### ISSUE TITLE
Not showing vehices

### ISSUE THREAD

**Issue by dsiluch** [barrykooij/wp-car-manager#75]
The plugin has been working great for 2 months

Now it wont load any of the vehicles. 

Plugin has been updated, all the vehicles are published, the plugin loads on the live website but wont list any vehicles

please help

**Comment by barrykooij** [comment]
Hey there,

This is most likely caused by a JavaScript error that another plugin or your theme is causing. For support please create a ticket here: https://wordpress.org/support/plugin/wp-car-manager

Cheers,
Barry
